global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['localhost:8080']
        labels:
          host: 'traefik'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          host: 'grafana-vps'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['localhost:8081']
        labels:
          host: 'grafana-vps'

  - job_name: 'process-exporter'
    static_configs:
      - targets: ['localhost:9256']
        labels:
          host: 'grafana-vps'

  - job_name: 'loki'
    static_configs:
      - targets: ['localhost:3100']
        labels:
          host: 'grafana-vps'

  - job_name: 'promtail'
    static_configs:
      - targets: ['localhost:9080']
        labels:
          host: 'grafana-vps'