server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: traefik
  static_configs:
  - targets:
      - localhost
    labels:
      job: traefik
      __path__: /traefik/logs/access.log
  pipeline_stages:
  - json:
      expressions:
        ClientHost: ClientHost
        RequestHost: RequestHost
        RequestMethod: RequestMethod
        RequestPath: RequestPath
        OriginStatus: OriginStatus
        DownstreamStatus: DownstreamStatus
        OriginDuration: OriginDuration
  - labels:
      ClientHost:
      RequestHost:
      RequestMethod:
      RequestPath:
      OriginStatus:
      DownstreamStatus: